name: Test Helm Deployment

on:
  workflow_dispatch:

jobs:
  helm-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Docker image
      - name: Build Docker image
        run: |
          docker build -t sample-app:latest app/

      # 3️⃣ Set up KinD cluster
      - name: Create KinD cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: ci-sample

      # 4️⃣ Wait for KinD nodes to be ready
      - name: Wait for nodes ready
        run: kubectl wait --for=condition=Ready nodes --all --timeout=120s

      # 5️⃣ Load Docker image into KinD
      - name: Load Docker image into KinD
        run: kind load docker-image sample-app:latest --name ci-sample

      # 6️⃣ Deploy Helm chart
      - name: Deploy Helm chart
        run: |
          helm install sample-app ./helm/sample-app \
            --set image.repository=sample-app \
            --set image.tag=latest \
            --wait --timeout 300s

      # 7️⃣ Verify pods
      - name: Check pods status
        run: kubectl get pods -o wide

      # 8️⃣ Optional: Describe pod logs for debugging
      - name: Debug pod
        run: |
          POD=$(kubectl get pods -l app=sample-app -o jsonpath='{.items[0].metadata.name}')
          kubectl describe pod $POD
          kubectl logs $POD
